# Generated by Django 3.1.3 on 2020-11-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HygienicStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('manager', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('birthid', models.IntegerField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.TextField()),
                ('standard', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('duration', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.patient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.place')),
            ],
        ),
        migrations.CreateModel(
            name='CovidTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitdays', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hygienicstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.hygienicstation')),
            ],
        ),
        migrations.CreateModel(
            name='Covidpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covidpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.covidtest')),
                ('hygienicstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.hygienicstation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.patient')),
            ],
        ),
    ]
