# Generated by Django 3.1.3 on 2020-11-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidpass',
            name='covidpass',
        ),
        migrations.AddField(
            model_name='covidpass',
            name='covidtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corona.covidtest'),
        ),
        migrations.AlterField(
            model_name='covidpass',
            name='hygienicstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corona.hygienicstation'),
        ),
    ]
