# Generated by Django 3.1.3 on 2020-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20201121_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidpass',
            name='testdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidpass',
            name='testresult',
            field=models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative')], max_length=3),
        ),
    ]
