# Generated by Django 3.1.3 on 2020-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20201121_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthid',
            field=models.CharField(max_length=15),
        ),
    ]
