# Generated by Django 3.1.3 on 2020-11-22 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corona', '0006_auto_20201122_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='covidpass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corona.covidpass'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
