# Generated by Django 3.1.3 on 2020-11-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_auto_20201124_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidtest',
            name='hygienicstation',
        ),
        migrations.AddField(
            model_name='covidtest',
            name='type',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
