# Generated by Django 3.1.3 on 2020-11-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0009_auto_20201124_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidpass',
            name='covidtest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corona.covidtest'),
        ),
    ]
