# Generated by Django 3.1.3 on 2020-11-27 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0010_auto_20201124_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='patient',
        ),
        migrations.AddField(
            model_name='hygienicstation',
            name='closehour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hygienicstation',
            name='openhour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covidpass',
            name='testresult',
            field=models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthid',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='place',
            name='standard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
